replicaCount: 1
image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-metering
  pullPolicy: IfNotPresent
  tag: "1.0.3"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 2000m
    memory: 3072Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  hosts:
    - host: your.domain.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: metering
                port:
                  number: 8080
  tls:
    - secretName: ca-secret
      hosts:
        - your.domain.com

autoPromotionEnabled: true