replicaCount: 1
image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-metering
  pullPolicy: IfNotPresent
  tag: "1.0.4"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 512Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  host: 
autoPromotionEnabled: true
jvmOption: ""