image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-metering
  pullPolicy: IfNotPresent
  tag: "1.0.30"

# Resource quota
resources:
  requests:
    cpu: 500m
    memory: 1.5G
  limits:
    cpu: 500m
    memory: 1.5G

# Readiness 
readinessInitialDelaySeconds: 30
readinessPeriodSeconds: 30

# Liveness
livenessInitialDelaySeconds: 60
livenessPeriodSeconds: 30

# JVM Option
jvm:
  enabled: true
  option: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:InitialRAMPercentage=50 -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=75"

# Service 
service:
  type: NodePort
  port: 8080
  nodePort: 30017
  ipamRange: 
  loadbalancerIP: 

# AutoScaling
autoscaling:
  enabled: true
  minReplicas: 12
  maxReplicas: 16
  targetCPUUtilizationPercentage: 90

# TimeZone
timezone: Asia/Seoul

# Delievery Policy
autoPromotionEnabled: true

# Injetct Config server
configServer:
  enabled: true