image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-metering
  pullPolicy: IfNotPresent
  tag: "1.0.26"

# Resource quota
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    memory: 1Gi

# Readiness 
readinessInitialDelaySeconds: 30
readinessPeriodSeconds: 30

# Liveness
livenessInitialDelaySeconds: 60
livenessPeriodSeconds: 30

# JVM Option
jvm:
  enabled: true
  option: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC"

# Service 
service:
  type: NodePort
  port: 8080
  nodePort: 30017
  ipamRange: 
  loadbalancerIP: 

# AutoScaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90

# TimeZone
timezone: Asia/Seoul

# Delievery Policy
autoPromotionEnabled: true

# Injetct Config server
configServer:
  enabled: true