replicaCount: 1
image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-metering
  pullPolicy: IfNotPresent
  tag: "1.0.12"

# Resource quota
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

# Readiness 
readinessInitialDelaySeconds: 30
readinessPeriodSeconds: 30

# Liveness
livenessInitialDelaySeconds: 60
livenessPeriodSeconds: 30

# JVM Option
jvm:
  enabled: true
  option: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC"

# Service 
service:
  type: NodePort
  port: 8080
  nodePort: 30017

# Ingress 
ingress:
  enabled: false
  host: 

# AutoScaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 85

# TimeZone
timezone: Asia/Seoul

# Delievery Policy
autoPromotionEnabled: true