
#  cloud:
#    config:
#      name: ccsp20-common,ccsp20-metering
#  config:
#    import: optional:configserver:http://localhost:8888
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      database-platform:
management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      org_name: CCS-DEV
      space_name: automation
      app_name: ccsp20-metering-graalvm
      cf_instance_id: ccsp20-metering-graalvm
    export:
      statsd:
        enabled: true
        host: telegraf-java.hubble-telegraf.svc.cluster.local
        port: 8125
        flavor: telegraf

spring:

  application:
    name: ccsp20-metering

  cloud:
    config:
      enabled: false

    compatibility-verifier:
      enabled: false

  jpa:

    show-sql: true
    generate-ddl: false

    database: postgresql
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  #      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://10.11.53.64:5432/meteringdb
    username: meteringwas
    password: devOps1!
    hikari:
      maximum-pool-size: 300
      minimum-idle: 80
      schema: meteringadm
  kafka:
    bootstrap-servers: 10.7.159.122:9092, 10.7.159.123:9092, 10.7.159.124:9092, 10.7.159.125:9092, 10.7.159.126:9092
    max-poll-interval-ms: 600000
    consumer:
      auto-offset-reset: earliest
      enable:
        auto:
          commit: true

  ##Async Thread
  task:
    execution:
      thread-name-prefix: meteringAsync-
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100

logging:
  level:
    com.hyundaiautoever.ccs.metering: DEBUG
transaction:
  logger:
    exclude:
      url: cloudfoundryapplication, swagger, actuator

metering:
  max-ten-minute-access-count: 200
  max-day-access-count: 300
  BLOCK_BY_API: BK02      # 서비스 요청 횟수 초과로 인한 차단(API미터링 관련 코드)
  SERVICE_SUCCESS: "0000"   #서비스요청성공
  MSG_FORMAT_INVALID: S999 #전문 형식 에러
  BLOCKED_RSON_10MIN: 1004 #CCSP PI미터링 차단(1004:10분, 1005:당일)
  BLOCKED_RSON_DAY: 1005   #CCSP API미터링 차단(1004:10분, 1005:당일)
  caridnullablewhitelist:
    /pushhistorylist.do
    , /getbadgecount.do
    , /readmsg.do
    , /delselectedpush.do
    , /popuppushhistory.do
    , /infolist_v2.do
    , /devicemapping.do
  ALLOW_ACCESS: 0
  ALLOW_BLOCK: 1
  DATA_NOT_VALID: 2

RETURN_CODE_TYPE:
  FAIL: F
  SUCCESS: S
  BLOCKED: B

server:
  tomcat:
    threads:
      max: 1000
      min-spare: 100
core:
  filter:
    exclude:
      - /actuator/**
      - /swagger/**

