server:
  metering:
    url: https://metering.apps.dev.hkccs.kr
  servlet:
    context-path: /metering/v1/
  tomcat:
    max-threads: 1000
    min-spare-threads: 100
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      database: POSTGRESQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://10.11.53.64:5432/meteringdb
    username: meteringwas
    password: P!ssw0rd
    hikari:
      maximum-pool-size: 300
      minimum-idle: 80
      schema: meteringadm
  zipkin:
    base-url: http://10.11.53.1:9411
  ##Async Thread
  task:
    execution:
      thread-name-prefix: meteringAsync-
      pool:
        ## 최초에 생성할 Pool 개수
        core-size: 10
        ## 몇개까지 Pool을 생성할 것인지 : Max TPS * 10%
        max-size: 160
      ##Async 처리 시 Queue Size(설정하지 않으면 Integer.MAX이기 때문에 성능에 문제가 발생함)
      #QueueCapacity를 CorePoolSize * MaxPoolSize * 2
      queue-capacity: 3200


logging:
  level:
    com.hyundaiautoever.ccs.metering: ERROR
