metering:
  max-ten-minute-access-count: 200
  max-day-access-count : 300
server:
  port: 8080
  servlet:
    context-path: /metering/v1/
spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/metering
    username: user
    hikari:
      maximum-pool-size: 4


