server:
  metering:
    url: https://metering.apps.dev.hkccs.kr
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      database: POSTGRESQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://10.11.53.64:5432/meteringdb
    username: meteringwas
    password: P!ssw0rd
    hikari:
      maximum-pool-size: 100
      minimum-idle: 80
      schema: meteringadm
  zipkin:
    base-url: http://10.11.53.1:9411

logging:
  level:
    com.hyundaiautoever.ccs.metering: INFO
