apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name:  {{ template "metering.fullname" . }}
spec:
  minAvailable: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: {{ template "metering.name" . }}
      release: {{ .Release.Name }}